inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Exclude:
    - lib/bipbip/version.rb

Performance/PushSplat:
  Enabled: false
