language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7

services:
  - memcached
  - mysql
  - redis-server

before_install:
  - gem update --system 2.1.11 #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
