language: ruby

rvm:
  - 2.0.0
  - 1.9.3

services:
  - memcached
  - mysql
  - redis-server
  - mongodb

before_install:
  - gem update --system 2.1.11 #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
