language: ruby
sudo: false

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3

services:
  - memcached
  - mysql
  - redis-server

notifications:
  email: false

# to avoid travis-ci issue since 2015-12-25
before_install:
  - gem update bundler
