copperegg:
  apikey: "YOUR_APIKEY"
  frequency: 10
  services:
  - memcached
memcached:
  group_name: "memcached"
  group_label: "Redis Metrics"
  dashboard: "Redis Dashboard"
  servers:
  -
    name: "server01"
    hostname: "localhost"
    port: 6379
